[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 1000
depth = 15
fail_on_revert = false

# BSCScan API configuration
[etherscan]
bsc_testnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api" }

# Rayls Testnet configuration
[rpc_endpoints]
rayls_testnet = "https://devnet-rpc.rayls.com"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
